### ISSUE TITLE
Graphviz sur serveur mutualisé?

### ISSUE THREAD

**Issue by jcovillers78114** [InfotelGLPI/archires#2]
Bonjour,
J'imagine que Graphviz est toujours nécessaire au fonctionnement du plugin ? Peut-on l'installer sur un serveur mutualisé ?

**Comment by tsmr** [comment]
Bonjour, non cela n'est plus nécessaire. J'utilise la même librairie que l'analyse d'impact désormais.

**Comment by jcovillers78114** [comment]
Merci pour ce retour rapide! Je viens de l'installer sur une 10.0.16 mais j'ai page blanche dans l'onglet Architecture réseau d'une machine. De mémoire il y avait une page de configuration pour choisir la map en DOT ou l'autre structure de schéma, mais je ne retrouve rien à part l'onglet "Architecture réseau" sur les machines

**Comment by tsmr** [comment]
il faut lancer l'action automatique CreateNetworkArchitecture maintenant

**Comment by jcovillers78114** [comment]
![2024-09-02 06_11_35-Window](https://github.com/user-attachments/assets/a5a72b2a-ec61-4c04-8fc6-358290a1f453)
Bonjour,
Après avoir lancé l'action automatique en manuel j'ai bien quelque chose qui s'implémente dans l'onglet archi réseau mais la page reste blanche. J'ai désactivé tous les plugins pour vérifier s'il y a une incompatibilité avec archires mais ce n'est pas le cas.

**Comment by tsmr** [comment]
des erreurs en mode debug ou dans la console du navigateur

**Comment by jcovillers78114** [comment]
Uncaught Exception Error: Undefined constant Glpi\Plugin\Hooks::SET_ITEM_IMPACT_ICON in /XXX/glpi/plugins/archires/inc/archires.class.php at line 733

**Comment by tsmr** [comment]
https://github.com/InfotelGLPI/archires/commit/336d0d17ac59becd9b654099689cc9633a8be50b

**Comment by jcovillers78114** [comment]
Ok ça fonctionne. Mais le graphique est vertical (généré de gauche à droite au lieu de haut en bas). Du coup les noms des machines se superposent et c'est peu lisible.
![2024-09-02 10_08_13-Window](https://github.com/user-attachments/assets/cd78e04d-bdd3-4ba2-8155-ad211a32c9f1)

**Comment by jcovillers78114** [comment]
Je note également que le graph généré contient toutes les entités même si elles ne communiquent pas entre elles par un matériel.
