### ISSUE TITLE
Page blanche

### ISSUE THREAD

**Issue by jcovillers78114** [InfotelGLPI/archires#3]
Bonjour,
Je viens d'installer le plugin sur une v10.0.16.
Dans l'onglet "Architecture réseau" je n'ai qu'une page blanche.
Je ne retrouve pas la page de configuration du plugin.
Merci

**Comment by tsmr** [comment]
Can you test this fix : 
https://github.com/InfotelGLPI/archires/commit/336d0d17ac59becd9b654099689cc9633a8be50b
